# -*- coding: utf-8 -*-
"""file._transformersipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYeK8-JH9dFkPSNCRE35UrRRwrMIkH4X
"""

import streamlit as st
from transformers import pipeline, CLIPProcessor, CLIPModel
from PIL import Image
import torch

# Load pipelines
@st.cache_resource
def load_pipeline():
    return {
        "sentiment": pipeline("sentiment-analysis",
                              model="distilbert-base-uncased-finetuned-sst-2-english"),
        "generator": pipeline("text-generation", model="gpt2"),
        "image_classifier": pipeline("image-classification",
                                    model="google/vit-base-patch16-224"),
        "asr": pipeline("automatic-speech-recognition",
                        model="openai/whisper-small")
    }

@st.cache_resource
def load_clip():
    model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
    processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
    return model, processor

# Load everything
pipelines = load_pipeline()
model, processor = load_clip()

# UI
st.title("🤖 AI Playground with Transformers")

task = st.sidebar.selectbox(
    "Choose a task:",
    ["Sentiment Analysis", "Text Generation",
     "Image Classification", "Speech to Text"]
)

# ------------------ SENTIMENT ------------------
if task == "Sentiment Analysis":
    text = st.text_area("Enter text:", "I love using transformers")

    if st.button("Analyze"):
        result = pipelines['sentiment'](text)[0]
        st.write(f"Sentiment: {result['label']}")
        st.write(f"Score: {result['score']:.4f}")

# ------------------ TEXT GENERATION ------------------
elif task == "Text Generation":
    prompt = st.text_area("Enter prompt:", "The quick brown fox")

    if st.button("Generate"):
        result = pipelines['generator'](
            prompt, max_length=50, num_return_sequences=1)
        st.write(result[0]['generated_text'])

# ------------------ IMAGE CLASSIFICATION ------------------
elif task == "Image Classification":
    uploaded_file = st.file_uploader(
        "Upload an image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_column_width=True)

        if st.button("Classify"):
            results = pipelines['image_classifier'](image)
            for result in results:
                st.write(f"{result['label']} : {result['score']:.4f}")

# ------------------ SPEECH TO TEXT ------------------
elif task == "Speech to Text":
    uploaded_file = st.file_uploader(
        "Upload audio", type=["mp3", "wav", "flac"])

    if uploaded_file is not None:
        audio_bytes = uploaded_file.read()
        st.audio(audio_bytes, format="audio/wav")

        if st.button("Transcribe"):
            result = pipelines['asr'](audio_bytes)
            st.write("Transcription:")
            st.write(result['text'])



